### ISSUE TITLE
Build Error in Production

### ISSUE THREAD

**Issue by devronhansen** [spatie/vue-table-component#29]
First of all, thank you for the awesome package.
I`ve got a problem only when im using yarn production:
ERROR in build.js from UglifyJs
Unexpected token: name (context) [./~/vue-table-component/dist/index.js:35069,0][build.js:95786,12] error Command failed with exit code 2

Everthing works perfectly if im using yarn dev.
I`m using vue cli with webpack-simple template.
Thank you in advance for your help.

**Comment by timacdonald** [comment]
Yea, I have also been getting this issue. Console output:

<img width="1440" alt="screen shot 2017-08-08 at 10 41 08 pm" src="https://user-images.githubusercontent.com/24803032/29072400-c8d3ddd6-7c8a-11e7-96fc-33844ef55fe4.png">


Log file mentioned in the above screenshot with the server domain as `REDACTED`

```
cat /home/forge/.npm/_logs/2017-08-08T12_40_54_115Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'production' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose run-script [ 'preproduction', 'production', 'postproduction' ]
5 info lifecycle @~preproduction: @
6 silly lifecycle @~preproduction: no script for preproduction, continuing
7 info lifecycle @~production: @
8 verbose lifecycle @~production: unsafe-perm in lifecycle true
9 verbose lifecycle @~production: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/forge/REDACTED/node_modules/.bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/home/forge/REDACTED/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle @~production: CWD: /home/forge/REDACTED
11 silly lifecycle @~production: Args: [ '-c',
11 silly lifecycle   'cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js' ]
12 silly lifecycle @~production: Returned: code: 2  signal: null
13 info lifecycle @~production: Failed to exec production script
14 verbose stack Error: @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid @
16 verbose cwd /home/forge/REDACTED
17 verbose Linux 4.4.0-87-generic
18 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "production"
19 verbose node v8.1.2
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 2
23 error @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
23 error Exit status 2
24 error Failed at the @ production script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 2, true ]
```

**Comment by sebastiandedeyne** [comment]
Having it too, gonna look into this as soon as I have some time for it

**Comment by sebastiandedeyne** [comment]
Fixed in `1.4.0-rc.8`, gonna tag a stable release soon!

**Comment by timacdonald** [comment]
Freak'in awesome.

**Comment by devronhansen** [comment]
thank you very much
